name = "TuePlots"
uuid = "7dc86ad5-723e-4492-bd0d-d0b58009a4c8"
authors = ["Nathanael Bosch <nathanael.bosch@uni-tuebingen.de> and contributors"]
version = "0.3.2"

[deps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
MakieCore = "0.4, 0.5, 0.6"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
